config/routes.rb
Rails.application.routes.draw do

	root 'articles#index'
	get 'articles/all' => 'articles#all'
	get 'articles/music' => 'articles#music'
	get 'articles/artists' => 'articles#artists'
	get 'articles/events' => 'articles#events'
	get '/signup' => 'users#new'
	post '/signup' => 'users#create'
	get '/profile' => 'users#show'
	resources :users

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :username, :presence => true, :uniqueness => true, :length => { :in => 6..15 }
	validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
	validates :password, :confirmation => true #password_confirmation attr
	validates_length_of :password, :in => 6..15, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # articles/all
  def all
  end

  def music
  end

  def artists
  end

  def events
  end
  
  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.fetch(:article, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Successfully Signed Up!"
			redirect_to :root
		else
			render 'new'
		end
	end

	private
	    def user_params
			params.require(:user).permit(:username, :email, :password, :password_confirmation)
	    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/all.html.erb
<div class="container-fluid" id="header">
	<%= image_tag( 'logo_black.png', :id => 'logo' ) %>
</div>

<nav class="navbar navbar-inverse" id="navbar">
	<div class="container-fluid text-center">
		<ul class="nav navbar-nav">
			<li><a href="/">Home</a></li>
			<li><a href="/articles/music">Music</a></li>
			<li><a href="">Artists</a></li>
			<li><a href="">Events</a></li>
		</ul>
	</div>
</nav>

<div class="container-fluid" id="mainContainer">
	<div class="row">
		<div class="col-xs-2">
			
		</div>
        <div id="allContent" class="col-xs-8 text-center">
        	<div id="article1">
	        	<br>
	        	<h4>Skream Sells Out Verizon Center</h4>
	        	<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
	        	<br>
	        	<%= image_tag( 'skream.jpg', :id => 'skream', :class => 'img-responsive' ) %>
	        	<br>
	        	<hr>
        	</div>
        	<div id="article2">
	        	<br>
	        	<h4>Bassnectar Gives Out Free Hugs</h4>
	        	<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
	        	<br>
	        	<%= image_tag( 'nectar.jpg', :id => 'nectar', :class => 'img-responsive' ) %>
	        	<br>
	        </div>
        </div>
		<div class="col-xs-2">
			
		</div>
    </div>
</div>

app/views/articles/artists.html.erb
<div class="container-fluid" id="header">
	<%= image_tag( 'logo_black.png', :id => 'logo' ) %>
</div>

<nav class="navbar navbar-inverse" id="navbar">
	<div class="container-fluid text-center">
		<ul class="nav navbar-nav">
			<li><a href="/articles/all">Articles</a></li>
			<li><a href="/articles/music">Music</a></li>
			<li><a href="/">Home</a></li>
			<li><a href="/articles/events">Events</a></li>
		</ul>
	</div>
</nav>

<div class="container-fluid" id="mainContainer">
	<div class="row">
		<div class="col-xs-2">
			
		</div>
        <div id="musicContent" class="col-xs-8 text-center">
        	<br>
        	<h4>Artists:</h4>
        	<p>Proin placerat laoreet metus quis finibus. Suspendisse in lacus sollicitudin, viverra ipsum ac, fringilla risus. Mauris vitae est convallis ex vulputate varius. Nunc semper blandit augue quis dapibus. Nullam feugiat, nisl et vulputate pharetra, massa ante ultrices dolor, eget porta sem purus id mauris. Vestibulum efficitur dolor sed arcu aliquet dapibus quis a eros. Sed iaculis cursus lorem interdum euismod. Aliquam pellentesque egestas ornare. Morbi efficitur in justo eu mattis. Nunc et libero facilisis, feugiat lacus et, semper dui. Proin lobortis vestibulum diam, at porttitor sem cursus in. Fusce in ultrices odio. Sed ac velit quis eros commodo vulputate.</p>
        	<p>In non sagittis urna, et consectetur dui. Fusce sodales faucibus nisl non auctor. Donec nisi ipsum, interdum vitae rutrum eu, vehicula vel est. Curabitur hendrerit nisl vitae lacus feugiat facilisis. Aenean pulvinar laoreet enim nec vestibulum. Ut in lorem ligula. Integer enim nisl, blandit vehicula mattis eu, finibus eget odio. Mauris id eleifend quam. Duis ut est sem. Sed laoreet, arcu a malesuada venenatis, arcu quam interdum massa, tempor laoreet turpis arcu sed orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis maximus nisl efficitur augue pulvinar, eu pharetra magna lobortis. Nullam suscipit nulla velit, sed commodo diam condimentum non. Donec posuere tempus lacus, non consequat leo vehicula a.</p>
        	<p>Praesent sit amet nulla vel neque rhoncus accumsan et molestie augue. Etiam iaculis mi non fringilla consectetur. Vestibulum auctor a est eget convallis. Nunc id ultricies lectus. Etiam vel mauris purus. Nulla semper vitae est dignissim elementum. Duis quis pellentesque mauris. In feugiat vulputate interdum. Donec luctus lacinia erat, et laoreet dolor consequat vitae. Proin vitae felis felis.</p>
        	<p>Cras eget orci fringilla, euismod quam a, rutrum mauris. Donec pellentesque id sem et blandit. Ut ante massa, tincidunt quis lectus ac, aliquet fermentum turpis. Etiam lacinia pretium purus, a interdum massa vehicula ut. Ut suscipit laoreet purus ut viverra. Aenean vitae sapien eget neque interdum aliquet quis et quam. Fusce et risus ultrices, scelerisque quam nec, tristique augue.</p>
        </div>
		<div class="col-xs-2">
			
		</div>
    </div>
</div>

app/views/articles/events.html.erb
<div class="container-fluid" id="header">
	<%= image_tag( 'logo_black.png', :id => 'logo' ) %>
</div>

<nav class="navbar navbar-inverse" id="navbar">
	<div class="container-fluid text-center">
		<ul class="nav navbar-nav">
			<li><a href="/articles/all">Articles</a></li>
			<li><a href="/articles/music">Music</a></li>
			<li><a href="/articles/artists">Artists</a></li>
			<li><a href="/">Home</a></li>
		</ul>
	</div>
</nav>

<div class="container-fluid" id="mainContainer">
	<div class="row">
		<div class="col-xs-2">
			
		</div>
        <div id="musicContent" class="col-xs-8 text-center">
        	<br>
        	<h4>Events:</h4>
        	<p>In non sagittis urna, et consectetur dui. Fusce sodales faucibus nisl non auctor. Donec nisi ipsum, interdum vitae rutrum eu, vehicula vel est. Curabitur hendrerit nisl vitae lacus feugiat facilisis. Aenean pulvinar laoreet enim nec vestibulum. Ut in lorem ligula. Integer enim nisl, blandit vehicula mattis eu, finibus eget odio. Mauris id eleifend quam. Duis ut est sem. Sed laoreet, arcu a malesuada venenatis, arcu quam interdum massa, tempor laoreet turpis arcu sed orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis maximus nisl efficitur augue pulvinar, eu pharetra magna lobortis. Nullam suscipit nulla velit, sed commodo diam condimentum non. Donec posuere tempus lacus, non consequat leo vehicula a.</p>
        	<p>Praesent sit amet nulla vel neque rhoncus accumsan et molestie augue. Etiam iaculis mi non fringilla consectetur. Vestibulum auctor a est eget convallis. Nunc id ultricies lectus. Etiam vel mauris purus. Nulla semper vitae est dignissim elementum. Duis quis pellentesque mauris. In feugiat vulputate interdum. Donec luctus lacinia erat, et laoreet dolor consequat vitae. Proin vitae felis felis.</p>
        	<p>Cras eget orci fringilla, euismod quam a, rutrum mauris. Donec pellentesque id sem et blandit. Ut ante massa, tincidunt quis lectus ac, aliquet fermentum turpis. Etiam lacinia pretium purus, a interdum massa vehicula ut. Ut suscipit laoreet purus ut viverra. Aenean vitae sapien eget neque interdum aliquet quis et quam. Fusce et risus ultrices, scelerisque quam nec, tristique augue.</p>
        </div>
		<div class="col-xs-2">
			
		</div>
    </div>
</div>

app/views/articles/index.html.erb
<% flash.each do |message_type, message| %>
	<div class="alert alert-<%= message_type %>" id="successAlert"><%= message %></div>
<% end %>

<div class="container-fluid" id="header">
	<img src="assets/logo_black.png" alt="Logo" id="logo">
	<div>
		<h5>A Site By:<h5>
		<h5>John W. Schmid</h5>
	</div>
	<div class="btn-group-vertical" id="userButtons">
		<a href="/signup" class="btn btn-primary">Sign Up</a>
		<a href="" class="btn btn-danger">Log In</a>
	</div>
</div>

<nav class="navbar navbar-inverse" id="navbar">
	<div class="container-fluid text-center">
		<ul class="nav navbar-nav">
			<li><a href="/articles/all">Articles</a></li>
			<li><a href="/articles/music">Music</a></li>
			<li><a href="/articles/artists">Artists</a></li>
			<li><a href="/articles/events">Events</a></li>
		</ul>
	</div>
</nav>

<div class="container-fluid" id="mainContainer">
	<div class="row">
        <div id="content" class="col-xs-9 text-center">
        	<div id="article1">
	        	<br>
	        	<h4>Skream Sells Out Verizon Center</h4>
	        	<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
	        	<br>
	        	<img src="assets/skream.jpg" alt="Skream" id="skream" class="img-responsive">
	        	<br>
	        	<hr>
        	</div>
        	<div id="article2">
	        	<br>
	        	<h4>Bassnectar Gives Out Free Hugs</h4>
	        	<p>"Fusce congue efficitur malesuada. Vivamus hendrerit diam tempus mauris lobortis, a consectetur nisi aliquam. Fusce tempus fringilla enim sit amet condimentum. Fusce nulla justo, fermentum eget laoreet ac, vulputate in ante. Nullam vestibulum turpis in magna auctor consectetur sit amet sed sem. Cras eget lacus nibh. Suspendisse tincidunt nisi nec aliquet sollicitudin. Morbi sit amet auctor est. In nisl urna, dignissim eu lorem vel, dignissim ultricies massa. Quisque egestas lacinia efficitur. Morbi lacinia interdum eros ac congue. Curabitur dapibus tellus ante, sed viverra sapien porta et. Sed ornare in nibh vel malesuada. In ut magna malesuada leo ornare iaculis."</p>
	        	<br>
	        	<img src="assets/nectar.jpg" alt="Nectar" id="nectar" class="img-responsive">
	        	<br>
	        </div>
        </div>
        <div id="sidebar" class="col-xs-3">
        	<br>
        	<h4>Upcoming</h4>
    		<ul>
				<li class="biglist">Blues Show</li>
					<ul>
						<li class="tinylist">Location: U Street Music Hall</li>
						<li class="tinylist">Date: Aug 25, 1991</li>
					</ul>
				<li class="biglist">Album Release Event</li>
					<ul>
						<li class="tinylist">Location: Flash</li>
						<li class="tinylist">Date: July 15, 2017</li>
					</ul>
				<li class="biglist">Rock Concert</li>
					<ul>
						<li class="tinylist">Location: Merriweather Post</li>
						<li class="tinylist">Date: Sept 12, 2017</li>
					</ul>
				<li class="biglist">Hip-Hop Event</li>
					<ul>
						<li class="tinylist">Location: 9:30 Club</li>
						<li class="tinylist">Date: Nov 7, 2017</li>
					</ul>
				<li class="biglist">EDM Concert</li>
					<ul>
						<li class="tinylist">Location: Merriweather Post</li>
						<li class="tinylist">Date: Nov 28, 2017</li>
					</ul>
			</ul>
        </div>
	</div>
</div>

app/views/articles/music.html.erb
<div class="container-fluid" id="header">
	<%= image_tag( 'logo_black.png', :id => 'logo' ) %>
</div>

<nav class="navbar navbar-inverse" id="navbar">
	<div class="container-fluid text-center">
		<ul class="nav navbar-nav">
			<li><a href="/articles/all">Articles</a></li>
			<li><a href="/">Home</a></li>
			<li><a href="/articles/artists">Artists</a></li>
			<li><a href="/articles/events">Events</a></li>
		</ul>
	</div>
</nav>

<div class="container-fluid" id="mainContainer">
	<div class="row">
		<div class="col-xs-2">
			
		</div>
        <div id="musicContent" class="col-xs-8 text-center">
        	<br>
        	<h4>Music:</h4>
        	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut bibendum lacus dignissim felis pellentesque, at fringilla lectus rutrum. Pellentesque ultrices nisl in accumsan elementum. Vivamus ornare, erat eget lacinia interdum, neque urna congue mauris, non semper odio felis non justo. Donec dapibus lorem sed congue lobortis. Vestibulum nec sem sit amet est porttitor aliquam. In in neque non est porttitor elementum. Ut ultrices, eros vel tempus consequat, eros purus dictum nunc, non posuere augue purus vitae enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In eget tellus tincidunt, convallis urna a, tristique sapien. Proin ultrices pulvinar sem, a ultrices mauris tempor at. Nulla a turpis sed enim efficitur tempor et vitae erat. Duis nec hendrerit tellus. Vestibulum magna arcu, feugiat consequat nisl ac, consequat iaculis nibh. Curabitur quis ligula eu lacus placerat tempus mollis gravida mi. Vestibulum lorem nisi, aliquam non mi tincidunt, mattis vulputate felis.</p>
        	<p>Proin placerat laoreet metus quis finibus. Suspendisse in lacus sollicitudin, viverra ipsum ac, fringilla risus. Mauris vitae est convallis ex vulputate varius. Nunc semper blandit augue quis dapibus. Nullam feugiat, nisl et vulputate pharetra, massa ante ultrices dolor, eget porta sem purus id mauris. Vestibulum efficitur dolor sed arcu aliquet dapibus quis a eros. Sed iaculis cursus lorem interdum euismod. Aliquam pellentesque egestas ornare. Morbi efficitur in justo eu mattis. Nunc et libero facilisis, feugiat lacus et, semper dui. Proin lobortis vestibulum diam, at porttitor sem cursus in. Fusce in ultrices odio. Sed ac velit quis eros commodo vulputate.</p>
        	<p>In non sagittis urna, et consectetur dui. Fusce sodales faucibus nisl non auctor. Donec nisi ipsum, interdum vitae rutrum eu, vehicula vel est. Curabitur hendrerit nisl vitae lacus feugiat facilisis. Aenean pulvinar laoreet enim nec vestibulum. Ut in lorem ligula. Integer enim nisl, blandit vehicula mattis eu, finibus eget odio. Mauris id eleifend quam. Duis ut est sem. Sed laoreet, arcu a malesuada venenatis, arcu quam interdum massa, tempor laoreet turpis arcu sed orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis maximus nisl efficitur augue pulvinar, eu pharetra magna lobortis. Nullam suscipit nulla velit, sed commodo diam condimentum non. Donec posuere tempus lacus, non consequat leo vehicula a.</p>
        	<p>Praesent sit amet nulla vel neque rhoncus accumsan et molestie augue. Etiam iaculis mi non fringilla consectetur. Vestibulum auctor a est eget convallis. Nunc id ultricies lectus. Etiam vel mauris purus. Nulla semper vitae est dignissim elementum. Duis quis pellentesque mauris. In feugiat vulputate interdum. Donec luctus lacinia erat, et laoreet dolor consequat vitae. Proin vitae felis felis.</p>
        	<p>Cras eget orci fringilla, euismod quam a, rutrum mauris. Donec pellentesque id sem et blandit. Ut ante massa, tincidunt quis lectus ac, aliquet fermentum turpis. Etiam lacinia pretium purus, a interdum massa vehicula ut. Ut suscipit laoreet purus ut viverra. Aenean vitae sapien eget neque interdum aliquet quis et quam. Fusce et risus ultrices, scelerisque quam nec, tristique augue.</p>
        </div>
		<div class="col-xs-2">
			
		</div>
    </div>
</div>

app/views/articles/unused_scaffolding/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/unused_scaffolding/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/unused_scaffolding/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/unused_scaffolding/show.html.erb
<p id="notice"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Amorphous Music</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class="container-fluid" id="header">
	<img src="assets/logo_black.png" alt="Logo" id="logo">
	<div>
		<h5>A Site By:<h5>
		<h5>John W. Schmid</h5>
	</div>
	<div class="btn-group-vertical" id="homeButton">
		<a href="/" class="btn btn-danger">Home</a>
	</div>
</div>

<nav class="navbar navbar-inverse" id="navbar">
	<div class="container-fluid text-center">
		<ul class="nav navbar-nav">
			<li><a href="/articles/all">Articles</a></li>
			<li><a href="/articles/music">Music</a></li>
			<li><a href="/articles/artists">Artists</a></li>
			<li><a href="/articles/events">Events</a></li>
		</ul>
	</div>
</nav>

<div id="bodyContainer">
		<% if @user.errors.any? %>
			<div id="error_explanation">
				<div class="alert alert-danger">
					The form contains <%= pluralize(@user.errors.count, "error") %>.
				</div>
				<ul>
					<% @user.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
	<div class="row">
	<div id="signUp" class="col-md-4 col-md-offset-4">
		<h4>Sign Up</h4>
		<%= form_for (@user), url: signup_path, :html => {:class => "form-horizontal"} do |f| %>
			<br>
			<div class="form-group form-inline">
				<%= f.label :username, "Username:", class: "control-label col-md-2" %>
				<%= f.text_field :username, class: "form-control" %>
			</div>
			<div class="form-group form-inline">
				<%= f.label :email, "Email:", class: "control-label col-md-2" %>
				<%= f.email_field :email, class: "form-control" %>
			</div>
			<div class="form-group form-inline">
				<%= f.label :password, "Password:", class: "control-label col-md-2" %>
				<%= f.password_field :password, class: "form-control" %>
			</div>
			<div class="form-group form-inline">
				<%= f.label :password_confirmation, "Confirmation:", class: "control-label col-md-2" %>
				<%= f.password_field :password_confirmation, class: "form-control" %>
			</div>
			<%= f.submit "Create Account", class: "btn btn-primary" %>
		<% end %>
	</div>
	</div>
</div>

app/views/users/show.html.erb
<h1>Profile</h1>
<p>Find me in app/views/users/show.html.erb</p>